# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Phone.ui'
#
# Created: Fri Mar 15 12:26:56 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 711)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, -1, 421, 331))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.key8 = QtGui.QPushButton(self.gridLayoutWidget)
        self.key8.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key8.sizePolicy().hasHeightForWidth())
        self.key8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.key8.setFont(font)
        self.key8.setObjectName("key8")
        self.gridLayout.addWidget(self.key8, 2, 1, 1, 1)
        self.key4 = QtGui.QPushButton(self.gridLayoutWidget)
        self.key4.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key4.sizePolicy().hasHeightForWidth())
        self.key4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.key4.setFont(font)
        self.key4.setObjectName("key4")
        self.gridLayout.addWidget(self.key4, 1, 0, 1, 1)
        self.key9 = QtGui.QPushButton(self.gridLayoutWidget)
        self.key9.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key9.sizePolicy().hasHeightForWidth())
        self.key9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.key9.setFont(font)
        self.key9.setObjectName("key9")
        self.gridLayout.addWidget(self.key9, 2, 2, 1, 1)
        self.key7 = QtGui.QPushButton(self.gridLayoutWidget)
        self.key7.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key7.sizePolicy().hasHeightForWidth())
        self.key7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.key7.setFont(font)
        self.key7.setObjectName("key7")
        self.gridLayout.addWidget(self.key7, 2, 0, 1, 1)
        self.key1 = QtGui.QPushButton(self.gridLayoutWidget)
        self.key1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key1.sizePolicy().hasHeightForWidth())
        self.key1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.key1.setFont(font)
        self.key1.setObjectName("key1")
        self.gridLayout.addWidget(self.key1, 0, 0, 1, 1)
        self.key3 = QtGui.QPushButton(self.gridLayoutWidget)
        self.key3.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key3.sizePolicy().hasHeightForWidth())
        self.key3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.key3.setFont(font)
        self.key3.setObjectName("key3")
        self.gridLayout.addWidget(self.key3, 0, 2, 1, 1)
        self.key2 = QtGui.QPushButton(self.gridLayoutWidget)
        self.key2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key2.sizePolicy().hasHeightForWidth())
        self.key2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.key2.setFont(font)
        self.key2.setObjectName("key2")
        self.gridLayout.addWidget(self.key2, 0, 1, 1, 1)
        self.key5 = QtGui.QPushButton(self.gridLayoutWidget)
        self.key5.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key5.sizePolicy().hasHeightForWidth())
        self.key5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.key5.setFont(font)
        self.key5.setObjectName("key5")
        self.gridLayout.addWidget(self.key5, 1, 1, 1, 1)
        self.key6 = QtGui.QPushButton(self.gridLayoutWidget)
        self.key6.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key6.sizePolicy().hasHeightForWidth())
        self.key6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.key6.setFont(font)
        self.key6.setObjectName("key6")
        self.gridLayout.addWidget(self.key6, 1, 2, 1, 1)
        self.key0 = QtGui.QPushButton(self.gridLayoutWidget)
        self.key0.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key0.sizePolicy().hasHeightForWidth())
        self.key0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.key0.setFont(font)
        self.key0.setObjectName("key0")
        self.gridLayout.addWidget(self.key0, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 25))
        self.menubar.setObjectName("menubar")
        self.menuPhone = QtGui.QMenu(self.menubar)
        self.menuPhone.setObjectName("menuPhone")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuPhone.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.key8.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.key4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.key9.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.key7.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.key1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.key3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.key2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.key5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.key6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.key0.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPhone.setTitle(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))

